# Generated by Django 5.0.3 on 2024-10-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('preferred_day', models.CharField(max_length=20)),
                ('preferred_timing', models.CharField(max_length=20)),
                ('additional_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
