# Generated by Django 5.0.3 on 2024-10-24 05:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_demosession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demosession',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='demosession',
            name='preferred_timing',
        ),
        migrations.AddField(
            model_name='demosession',
            name='preferred_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demosession',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
